#############################################################################################################################
# Bilger HTPC Server - Docker Compose for Guacamole web client, the guacd server and a postgres database.
#                                                                                                                           #
#############################################################################################################################
version: '3'
#############################################################################################################################
# SERVICES TO LAUNCH #
#############################################################################################################################
services:
  # ------------------------------------------------------------------------------------------------------------------------- GUACAMOLE - 
  #  Guacamole web based remote access client
  # -------------------------------------------------------------------------------------------------------------------------
  guacamole: 
    container_name: guacamole 
    image: oznu/guacamole
    restart: unless-stopped
    ports:
      - 18989:8080
    volumes:
      - ./config/guacamole:/config 
    #environment:
    #  - EXTENSIONS=auth-noauth

  guacamole2: 
    container_name: guacamole2
    image: oznu/guacamole
    restart: unless-stopped
    ports:
      - 18988:8080
    volumes:
      - ./config/guacamole2:/config 
    #environment:
    #  - EXTENSIONS=auth-noauth

#############################################################################################################################
# NETWORKS #
#############################################################################################################################
networks:
  default:
    external:
      name: media-server
