#############################################################################################################################
# Bilger Openmediavault Server - Docker Compose for  Pi-hole - Network-wide Ad Blocking                                     #
#                                                                                                                           #
#############################################################################################################################
version: '3'

#############################################################################################################################
# SERVICES TO LAUNCH                                                                                                        #
#############################################################################################################################
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    #network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"
      - "8010:80/tcp"
      - "8011:443/tcp"
    volumes:
      - ./config/pihole/:/etc/pihole/
      - ./config/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}      
    dns:
      - 127.0.0.1
      - 192.168.1.9
    cap_add:
      - NET_ADMIN

#############################################################################################################################
# NETWORKS #
#############################################################################################################################
networks:
  default:
    external:
      name: media-server
